# syntax=docker/dockerfile:1

FROM node:24-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

COPY . ./
RUN npm run build


FROM caddy:2.11.4-alpine AS runtime

COPY Caddyfile.k8s /etc/caddy/Caddyfile

COPY --from=build /app/dist/frontend/browser/ /srv/

EXPOSE 80 8081
