spring:
  application:
    name: FileDrop

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 510MB

  modulith:
    events:
      republish-outstanding-events-on-restart:  true
      jdbc:
        schema-initialization:
          enabled: true




application:

  filedrop:
    temporary-storage:
      directory: ${FILEDROP_TEMP_DIR:${java.io.tmpdir}/filedrop}

  file:
    max-size: 100MB
    expiration:
      min: 1m
      max: 7d
