spring:
  application:
    name: FileDrop

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 510MB

  modulith:
    events:
      republish-outstanding-events-on-restart:  true
      jdbc:
        schema-initialization:
          enabled: true




application:
  file:
    max-size: 500MB
    expiration:
      min: 1m
      max: 7d
