apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: clamav-data
  namespace: filedrop

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: clamav
  namespace: filedrop

spec:
  replicas: 1

  selector:
    matchLabels:
      app: clamav

  template:
    metadata:
      labels:
        app: clamav

    spec:
      containers:
        - name: clamav
          image: clamav/clamav:latest

          ports:
            - containerPort: 3310

          volumeMounts:
            - name: signatures
              mountPath: /var/lib/clamav

          startupProbe:
            tcpSocket:
              port: 3310
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 3310
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3310
            periodSeconds: 30

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi

      volumes:
        - name: signatures
          persistentVolumeClaim:
            claimName: clamav-data

---
apiVersion: v1
kind: Service

metadata:
  name: clamav
  namespace: filedrop

spec:
  type: ClusterIP

  selector:
    app: clamav

  ports:
    - port: 3310
      targetPort: 3310