apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: filedrop
  namespace: filedrop

  annotations:
    # The "letsencrypt" resolver is configured in 05-traefik-tls.yaml.
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

spec:
  ingressClassName: traefik

  rules:
    # Must match the hostname in FILEDROP_BASE_URL.
    - host: filedrop-prod.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: filedrop-backend
                port:
                  number: 8080

          - path: /
            pathType: Prefix
            backend:
              service:
                name: filedrop-frontend
                port:
                  number: 80
